#!/usr/bin/env python3
"""
agents-architect scaffold.py — create the standard plugin directory tree and placeholder files.

Usage:
    python3 scaffold.py <target-dir> --name <plugin-name> [--namespace <ns>]

Creates:
    target-dir/
    ├── .claude-plugin/plugin.json
    ├── .claude-plugin/marketplace.json
    ├── skills/
    ├── commands/<ns>/
    ├── agents/
    ├── hooks/hooks.json
    ├── scripts/
    ├── <plugin-name>/references/
    ├── <plugin-name>/templates/
    ├── README.md
    ├── LICENSE (MIT)
    └── CHANGELOG.md
"""
import argparse
import json
import sys
from pathlib import Path

MIT_LICENSE = """MIT License

Copyright (c) 2026 {author}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
"""


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("target")
    p.add_argument("--name", required=True)
    p.add_argument("--namespace")
    p.add_argument("--author", default="Unknown")
    p.add_argument("--email", default="")
    p.add_argument("--description", default="")
    args = p.parse_args()

    ns = args.namespace or args.name
    root = Path(args.target).resolve()
    root.mkdir(parents=True, exist_ok=True)

    dirs = [
        ".claude-plugin",
        "skills",
        f"commands/{ns}",
        "agents",
        "hooks",
        "scripts",
        f"{args.name}/references",
        f"{args.name}/templates",
    ]
    for d in dirs:
        (root / d).mkdir(parents=True, exist_ok=True)

    manifest = {
        "name": args.name,
        "version": "0.1.0",
        "description": args.description or f"Generated by agents-architect for {args.name}.",
        "author": {"name": args.author, "email": args.email},
        "license": "MIT",
        "keywords": [],
    }
    (root / ".claude-plugin" / "plugin.json").write_text(json.dumps(manifest, indent=2) + "\n")

    marketplace = {
        "name": f"{args.name}-marketplace",
        "owner": {"name": args.author, "email": args.email},
        "description": f"Marketplace for {args.name}.",
        "plugins": [{"name": args.name, "source": "./", "version": "0.1.0"}],
    }
    (root / ".claude-plugin" / "marketplace.json").write_text(json.dumps(marketplace, indent=2) + "\n")

    (root / "hooks" / "hooks.json").write_text(json.dumps({"hooks": {}}, indent=2) + "\n")
    (root / "README.md").write_text(f"# {args.name}\n\n{args.description}\n\nGenerated by agents-architect.\n")
    (root / "LICENSE").write_text(MIT_LICENSE.format(author=args.author))
    (root / "CHANGELOG.md").write_text("# Changelog\n\n## 0.1.0\n- Initial scaffold.\n")

    print(f"Scaffolded {args.name} at {root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
